"""
2020 Oil Crash Retrospective — Priority 1.

Compares the model's 2019 pre-crisis Right Now Risk rankings against the
actual 2020 outcomes recorded in data/reference/imf_weo_2020_outcomes.csv.

Workflow
--------
1. Load the historical index panel (outputs/tables/historical_risk_index.csv)
   and extract the 2019 snapshot (last full pre-crisis year).
2. Load actual 2020 outcomes from data/reference/imf_weo_2020_outcomes.csv.
3. Join on country_code_a3, compute rank_error and a hit/miss flag.
4. Compute Spearman rank correlation between model_rank_2019 and
   outcome_severity_rank (1 = worst actual outcome).
5. Export to outputs/tables/retrospective_2020.csv.

Key functions
-------------
load_outcomes            Load imf_weo_2020_outcomes.csv
run_2020_retrospective   Join model pre-crisis ranks with 2020 actuals
summarize_retrospective  High-level accuracy metrics
export_retrospective     Write to CSV

Usage (from project root)
--------------------------
    python -m src.model.retrospective
"""

from __future__ import annotations

import argparse
import logging
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd

log = logging.getLogger(__name__)

# ── Paths ──────────────────────────────────────────────────────────────────────

_ROOT = Path(__file__).resolve().parents[2]

OUTCOMES_PATH    = _ROOT / "data" / "reference" / "imf_weo_2020_outcomes.csv"
HIST_INDEX_PATH  = _ROOT / "outputs" / "tables" / "historical_risk_index.csv"
OUTPUT_PATH      = _ROOT / "outputs" / "tables" / "retrospective_2020.csv"

_PRE_CRISIS_YEAR = 2019
_CRISIS_YEAR     = 2020
_HIT_THRESHOLD   = 3   # ±rank positions counted as a "close call" (not a miss)


# ── Correlation helpers (no scipy) ────────────────────────────────────────────

def _spearman_r(x: list[float], y: list[float]) -> float:
    """Spearman rank correlation without scipy."""
    rx = pd.Series(x, dtype=float).rank()
    ry = pd.Series(y, dtype=float).rank()
    return float(np.corrcoef(rx.values, ry.values)[0, 1])


def _spearman_pvalue(r: float, n: int) -> float:
    """Two-tailed p-value via Fisher z-transform approximation (n ≥ 5)."""
    if n < 3 or abs(r) >= 1.0:
        return float("nan")
    z = math.atanh(r) * math.sqrt(max(n - 3, 1))
    return float(math.erfc(abs(z) / math.sqrt(2)))


# ── Data loaders ──────────────────────────────────────────────────────────────

def load_outcomes(path: Path = OUTCOMES_PATH) -> pd.DataFrame:
    """Load the IMF WEO 2020 actual outcomes reference CSV.

    Args:
        path: Path to imf_weo_2020_outcomes.csv.

    Returns:
        DataFrame with one row per country containing 2020 actual outcomes.

    Raises:
        FileNotFoundError: If the CSV does not exist.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Outcomes file not found: {path}")
    df = pd.read_csv(path)
    df["imf_emergency_program"] = df["imf_emergency_program"].map(
        {"True": True, "False": False, True: True, False: False}
    )
    log.info("Loaded %d outcome rows from %s", len(df), path)
    return df


def _load_hist_index(path: Path) -> pd.DataFrame:
    """Load the historical risk index panel (generated by historical_index.py)."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Historical index not found: {path}  "
            "Run: python -m src.model.historical_index"
        )
    return pd.read_csv(path)


# ── Core retrospective function ────────────────────────────────────────────────

def run_2020_retrospective(
    outcomes_df: pd.DataFrame | None = None,
    hist_index_df: pd.DataFrame | None = None,
    pre_crisis_year: int = _PRE_CRISIS_YEAR,
    outcomes_path: Path = OUTCOMES_PATH,
    hist_index_path: Path = HIST_INDEX_PATH,
) -> pd.DataFrame:
    """Join pre-crisis model rankings with 2020 actual outcomes.

    For each country the function records:
    - model_rank_precris: right_now_risk rank in *pre_crisis_year* (ascending = best)
    - outcome_severity_rank: actual 2020 GDP severity rank from IMF WEO (1 = worst)
    - rank_error: |model_rank_precris − outcome_severity_rank|
    - model_predicted_top5: whether model placed the country in its top-5 highest risk
    - actually_top5: whether the country ended up in the top-5 worst outcomes
    - hit: True if rank_error ≤ _HIT_THRESHOLD
    - gdp_growth_2020_pct, fiscal_balance_2020_pct_gdp, imf_emergency_program

    Args:
        outcomes_df:     Pre-loaded outcomes DataFrame (None → load from CSV).
        hist_index_df:   Pre-loaded historical index panel (None → load from CSV).
        pre_crisis_year: Year to use as pre-crisis model snapshot (default 2019).
        outcomes_path:   Path to imf_weo_2020_outcomes.csv.
        hist_index_path: Path to historical_risk_index.csv.

    Returns:
        DataFrame with one row per country, sorted by outcome_severity_rank.

    Raises:
        FileNotFoundError: If required inputs are missing.
        ValueError: If pre_crisis_year is absent from the historical index.
    """
    if outcomes_df is None:
        outcomes_df = load_outcomes(outcomes_path)
    if hist_index_df is None:
        hist_index_df = _load_hist_index(hist_index_path)

    # Extract pre-crisis snapshot and compute model rank
    if "year" not in hist_index_df.columns:
        raise ValueError("historical_risk_index.csv has no 'year' column.")
    snap = hist_index_df[hist_index_df["year"] == pre_crisis_year].copy()
    if snap.empty:
        raise ValueError(
            f"Year {pre_crisis_year} not found in historical index. "
            f"Available years: {sorted(hist_index_df['year'].unique())}"
        )

    snap["model_rank_precris"] = (
        snap["right_now_risk_score"]
        .rank(ascending=False, method="min", na_option="bottom")
        .astype(int)
    )

    keep_model = ["country_code_a3", "right_now_risk_score", "model_rank_precris",
                  "fiscal_stress_score", "reserve_runway_risk",
                  "social_stability_risk", "chain_transmission_severity",
                  "missing_components"]
    keep_model = [c for c in keep_model if c in snap.columns]
    snap_slim  = snap[keep_model].copy()

    # Merge with outcomes
    keep_out = [
        "country_code_a3", "country_label", "country_name",
        "gdp_growth_2020_pct", "fiscal_balance_2020_pct_gdp",
        "imf_emergency_program", "outcome_severity_rank",
        "confidence",
    ]
    keep_out = [c for c in keep_out if c in outcomes_df.columns]
    out_slim  = outcomes_df[keep_out].copy()

    merged = out_slim.merge(snap_slim, on="country_code_a3", how="left")

    # Derived columns
    merged["rank_error"] = (
        (merged["outcome_severity_rank"] - merged["model_rank_precris"]).abs()
    )
    merged["hit"] = merged["rank_error"] <= _HIT_THRESHOLD

    n_countries = len(merged)
    top5_thresh = min(5, n_countries // 2)
    merged["model_predicted_top5"]  = merged["model_rank_precris"]   <= top5_thresh
    merged["actually_top5"]         = merged["outcome_severity_rank"] <= top5_thresh

    # Sort by actual severity
    merged = merged.sort_values("outcome_severity_rank").reset_index(drop=True)

    log.info(
        "Retrospective %d→%d: %d countries  hit_rate=%.1f%%  rank_error_mean=%.2f",
        pre_crisis_year, _CRISIS_YEAR,
        len(merged),
        merged["hit"].mean() * 100,
        merged["rank_error"].mean(),
    )
    return merged


# ── Summary metrics ────────────────────────────────────────────────────────────

def summarize_retrospective(df: pd.DataFrame) -> dict[str, object]:
    """Compute high-level accuracy metrics for the retrospective.

    Args:
        df: Output of :func:`run_2020_retrospective`.

    Returns:
        Dict with keys: n_countries, hit_rate, rank_error_mean, rank_error_max,
        spearman_r, spearman_p, top5_precision, top5_recall, pre_crisis_year,
        crisis_year, hit_threshold.

    Raises:
        ValueError: If df is empty or missing required columns.
    """
    if df.empty:
        raise ValueError("Empty retrospective DataFrame — cannot summarize.")

    required = {"outcome_severity_rank", "model_rank_precris", "hit",
                "model_predicted_top5", "actually_top5"}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns: {sorted(missing)}")

    valid = df.dropna(subset=["outcome_severity_rank", "model_rank_precris"])
    n = len(valid)

    r = _spearman_r(
        valid["model_rank_precris"].tolist(),
        valid["outcome_severity_rank"].tolist(),
    )
    p = _spearman_pvalue(r, n)

    top5_predicted = valid[valid["model_predicted_top5"]]
    tp = int((top5_predicted["actually_top5"]).sum())
    precision = tp / len(top5_predicted) if len(top5_predicted) else float("nan")
    recall    = tp / int(valid["actually_top5"].sum()) if valid["actually_top5"].any() else float("nan")

    return {
        "pre_crisis_year":  _PRE_CRISIS_YEAR,
        "crisis_year":      _CRISIS_YEAR,
        "n_countries":      n,
        "hit_threshold":    _HIT_THRESHOLD,
        "hit_rate":         round(float(valid["hit"].mean()), 4),
        "rank_error_mean":  round(float(valid["rank_error"].mean()), 2),
        "rank_error_max":   int(valid["rank_error"].max()),
        "spearman_r":       round(r, 4),
        "spearman_p":       round(p, 4),
        "top5_precision":   round(precision, 4) if not math.isnan(precision) else float("nan"),
        "top5_recall":      round(recall, 4)    if not math.isnan(recall)    else float("nan"),
    }


# ── Export ─────────────────────────────────────────────────────────────────────

def export_retrospective(
    df: pd.DataFrame,
    output_path: Path = OUTPUT_PATH,
) -> Path:
    """Write retrospective results to CSV.

    Args:
        df:          Output of :func:`run_2020_retrospective`.
        output_path: Destination path (parent created if absent).

    Returns:
        Resolved absolute path of the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    log.info("Retrospective exported: %d rows → %s", len(df), output_path)
    return output_path.resolve()


# ── CLI ────────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m src.model.retrospective",
        description=(
            "Priority 1 — 2020 Oil Crash Retrospective.\n"
            "Compares pre-crisis model rankings against 2020 IMF WEO outcomes."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--output", metavar="PATH", default=str(OUTPUT_PATH),
                   help=f"Destination CSV (default: {OUTPUT_PATH}).")
    p.add_argument("--pre-crisis-year", type=int, default=_PRE_CRISIS_YEAR,
                   help=f"Pre-crisis snapshot year (default: {_PRE_CRISIS_YEAR}).")
    p.add_argument("--log-level", default="INFO",
                   choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                   help="Logging verbosity (default: INFO).")
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    try:
        df = run_2020_retrospective(pre_crisis_year=args.pre_crisis_year)
    except (FileNotFoundError, ValueError) as exc:
        log.error("Retrospective failed: %s", exc)
        return 1

    export_retrospective(df, Path(args.output))

    try:
        summary = summarize_retrospective(df)
        log.info(
            "Summary: n=%d  hit_rate=%.1f%%  spearman_r=%.3f (p=%.4f)  "
            "top5 precision=%.2f recall=%.2f",
            summary["n_countries"],
            summary["hit_rate"] * 100,
            summary["spearman_r"],
            summary["spearman_p"],
            summary["top5_precision"] if not math.isnan(summary["top5_precision"]) else float("nan"),
            summary["top5_recall"]    if not math.isnan(summary["top5_recall"])    else float("nan"),
        )
    except ValueError as exc:
        log.warning("Could not summarize: %s", exc)

    return 0


if __name__ == "__main__":
    sys.exit(main())
